<?= $this->doctype() ?>

<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('JS Peças')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->appendStylesheet('https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css')
            ->appendStylesheet($this->basePath('../../js/ext-6.2.0/theme-neptune/resources/theme-neptune-all.css'))
            // ->appendStylesheet($this->basePath('/js/ext-6.2.0/theme-classic/resources/theme-classic-all.css'))
            ->appendStylesheet($this->basePath('../../js/noty-3.1.4/noty.min.css'))
            ->appendStylesheet($this->basePath('css/style.css?_dc='.md5(date('H:m:s:u'))))
            ->appendStylesheet($this->basePath('css/cores.css?_dc='.md5(date('H:m:s:u'))))
        ?>

        <!-- Scripts -->

        <!-- Versão 9 funciona -->
        <!-- <script src='../../js/highcharts-9.0.1/code/stock/highstock.js'></script>
        <script>
            var Highstock = Highcharts;
            Highcharts = null;
        </script>
        <script src='../../js/highcharts-9.0.1/code/highcharts.js'></script> -->

        <script src='../../js/highcharts-8.2.0/code/stock/highstock.js'></script>
        <script src='../../js/highcharts-8.2.0/code//modules/data.js'></script>
        <script src='../../js/highcharts-8.2.0/code//modules/heatmap.js'></script>
        <script src='../../js/highcharts-8.2.0/code//modules/exporting.js'></script>
        <script src='../../js/highcharts-8.2.0/code//modules/export-data.js'></script>
        <script src='../../js/highcharts-8.2.0/code//modules/accessibility.js'></script>
        <script>
            var Highstock = Highcharts;
            Highcharts = null;
        </script>
        <script src='../../js/highcharts-8.2.0/code/highcharts.js'></script>
        <script src='../../js/highcharts-8.2.0/code/highcharts-more.js'></script>
        <?= $this->headScript()
            // ->appendFile($this->basePath('../../js/highcharts-8.2.0/code/highcharts.js')) 
            // ->appendFile($this->basePath('../../js/highcharts-8.2.0/code/highstock.js'))
            // ->appendFile($this->basePath('../../js/highcharts-8.2.0/code/highcharts-more.js'))
            ->appendFile($this->basePath('../../js/highcharts-8.2.0/code/modules/data.js'))
            ->appendFile($this->basePath('../../js/highcharts-8.2.0/code/modules/exporting.js'))
            ->appendFile($this->basePath('../../js/highcharts-8.2.0/code/modules/boost.js'))
            // ->appendFile($this->basePath('../../js/highcharts-8.2.0/code/modules/full-screen.js'))
            ->appendFile($this->basePath('../../js/highcharts-8.2.0/code/modules/export-data.js'))
            ->appendFile($this->basePath('../../js/highcharts-8.2.0/code/modules/accessibility.js'))
            ->appendFile($this->basePath('../../js/highcharts-8.2.0/code/modules/heatmap.js'))
            ->appendFile($this->basePath('../../js/jquery-3.4.1.min.js'))
            ->appendFile($this->basePath('../../js/ext-6.2.0/ext-all.js'))
            ->appendFile($this->basePath('../../js/ext-6.2.0/locale-pt_BR.js'))
            ->appendFile($this->basePath('../../js/noty-3.1.4/noty.min.js'))
            ->appendFile($this->basePath('app/Bootstrap.js?_dc='.md5(date('H:m:s:u'))))
            ->appendScript("var BASEURL = '".$this->basePath()."'", $type = 'text/javascript')
            ->appendScript("var USUARIO = '".$this->usuario()."'", $type = 'text/javascript')
        ?>
    </head>
    <body>
        <style>
            .x-grid-item {
                font: normal 12px/13px helvetica, arial, verdana, sans-serif;
            }

            .x-grid .x-grid-row .x-grid-cell-text-green .x-grid-cell-inner{
                color: #5d8800;
            }

            .x-grid .x-grid-row .x-grid-cell-text-red .x-grid-cell-inner{
                color: #df180d;
            }

            .x-grid .x-grid-row .x-grid-cell-text-yellow .x-grid-cell-inner{
                color: #f7a700;
            }

            .x-grid .x-grid-row .x-grid-cell-green .x-grid-cell-inner{
                color: #ffffff;
                background-color: #70a401;
            }

            .x-grid .x-grid-row .x-grid-cell-blue .x-grid-cell-inner{
                color: #ffffff;
                background-color: #4285F4;
            }

            .x-grid .x-grid-row .x-grid-cell-green2 .x-grid-cell-inner{
                color: #ffffff;
                background-color: #7db308;
            }

            .x-grid .x-grid-row .x-grid-cell-yellow .x-grid-cell-inner{
                color: #ffffff;
                background-color: #f7a700;
            }

            .x-grid .x-grid-row .x-grid-cell-red .x-grid-cell-inner{
                color: #ffffff;
                background-color: #fb1e12;
            }

            .x-grid-cell-green-border .x-grid-cell-inner{
                color: #6b8b3b;
                border: 1px solid #9bcc54;
                background-color: #cdefa6;
            }

            .x-grid-row-selected .x-grid-cell-green-border .x-grid-cell-inner,
            .x-grid-row-over .x-grid-cell-green-border .x-grid-cell-inner{
                color: #587232;
                border: 1px solid #8fba50;
                background-color: #b3ec72;
            }

            .x-grid-cell-red-border .x-grid-cell-inner{
                color: #cf3738;
                border: 1px solid #ffacad;
                background-color: #ffd5d5;
            }

            .x-grid-row-selected .x-grid-cell-red-border .x-grid-cell-inner,
            .x-grid-row-over .x-grid-cell-red-border .x-grid-cell-inner{
                color: #bc3435;
                border: 1px solid #f99799;
                background-color: #ffb1b1;
            }

            .x-grid-cell-yellow-border .x-grid-cell-inner{
                color: #b79000;
                border: 1px solid #e7bd72;
                background-color: #fff3a3;
            }

            .x-grid-row-selected .x-grid-cell-yellow-border .x-grid-cell-inner,
            .x-grid-row-over .x-grid-cell-yellow-border .x-grid-cell-inner{
                color: #a78300;
                border: 1px solid #efba52;
                background-color: #ffed72;
            }

            .x-grid .x-grid-row .x-grid-cell-purple .x-grid-cell-inner{
                color: #ffffff;
                background-color: #9a59b5;
            }

            .x-grid .x-grid-row .x-grid-cell-orange .x-grid-cell-inner{
                color: #ffffff;
                background-color: #fb5e00;
            }

            .x-grid-cell-text-through-green {
                text-decoration: line-through;
                color: #6b8b3b;
            }

            .x-column-header {​​

                border-right: 1px solid #c2c2c2;
                color: #666;
                font: bold 12px/13px helvetica, arial, verdana, sans-serif;
                outline: 0;
                background-color: #f5f5f5;
            }​​

            .x-grid-item-selected {​​

                color: #000;
                background-color: #c2f2faa1;
            }​​
        </style>
        <?= $this->inlineScript() ?>
        <?= $this->content ?>
    </body>
</html>
